---
title: "AXH_DESeq-PCA_Pdam"
author: "Mike Connelly"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/scripts/EAPSI.HW-WT-master/")
```
## Regularized-log transformations
```{r, include=FALSE}
      rld_anti <- rlogTransformation(dds_anti, blind = TRUE)
      rld_heat <- rlogTransformation(dds_heat, blind = TRUE)
      rld_anti.heat <- rlogTransformation(dds_anti.heat, blind = TRUE)
      rld_antixheat <- rlogTransformation(dds_antixheat, blind = TRUE)
###
      rld_HW1 <- rlogTransformation(dds_HW1, blind = TRUE)
      rld_HW2 <- rlogTransformation(dds_HW2, blind = TRUE)
      rld_WT1 <- rlogTransformation(dds_WT1, blind = TRUE)
      rld_WT2 <- rlogTransformation(dds_WT2, blind = TRUE)
```
Set theme, colors and shapes for ggplot2 plotting
```{r}
theme_set(theme_bw())
condcolors <- c("#00CCCC", "#FFCC33", "#CC0033", "#0000FF", "#FF6600", "#FF66FF")
condcolors_anti <- c("#00CCCC", "#0000FF")
condcolors_heat <- c("#0000FF", "#FF6600")
condcolors_anti.heat <- c("#0000FF", "#FFCC33")
condcolors_antixheat <- c("#0000FF", "#FF6600", "#00CCCC", "#FFCC33")
###
condfillcolors <- c("#99FFFF", "#FFFF66", "#FF6666", "#99CCFF", "#FFCC99", "#FFCCFF")
condfillcolors_antixheat <- c("#99CCFF", "#FFCC99", "#99FFFF", "#FFFF66")
colshapes <- c(18, 9, 16, 10)
colcolors <- c("#CCFFCC", "#99FFCC", "#CCFFFF", "#99CCFF")
```
Set factor orders 
```{r}
stable_samples_anti$Treatment <- factor(stable_samples_anti$Treatment, levels = c("control", "Antibiotics"), ordered = TRUE)
stable_samples_heat$Treatment <- factor(stable_samples_heat$Treatment, levels = c("control", "Heat"), ordered = TRUE)
stable_samples_anti.heat$Treatment <- factor(stable_samples_anti.heat$Treatment, levels = c("control", "Antibiotics.Heat"), ordered = TRUE)
stable_samples_antixheat$Treatment <- factor(stable_samples_antixheat$Treatment, levels = c("control", "Heat", "Antibiotics", "Antibiotics.Heat"), ordered = TRUE)
```

```{r}
plotPCA.custom <-  function(object, intgroup="Treatment", ntop=500, returnData=FALSE, pcs = c(1,2))
{
 stopifnot(length(pcs) == 2)    ### added this to check number of PCs ####
  # calculate the variance for each gene
  rv <- rowVars(assay(object))
  # select the ntop genes by variance
  select <- order(rv, decreasing=TRUE)[seq_len(min(ntop, length(rv)))]
  # perform a PCA on the data in assay(x) for the selected genes
  pca <- prcomp(t(assay(object)[select,]))
  # the contribution to the total variance for each component
  percentVar <- pca$sdev^2 / sum( pca$sdev^2 )
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop=FALSE])
  # add the intgroup factors together to create a new grouping factor
  group <- if (length(intgroup) > 1) {
    factor(apply( intgroup.df, 1, paste, collapse=" : "))
  } else {
    colData(object)[[intgroup]]
  }
  # assemble the data for the plot
  ########## Here we just use the pcs object passed by the end user ####
  d <- data.frame(PC1=pca$x[,pcs[1]], PC2=pca$x[,pcs[2]], group=group, intgroup.df, name=colnames(object))
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:2]
    return(d)
  }
  
  # extract loadings
}
```

```{r}
PCA.load <-  function(object, intgroup="Treatment", ntop=500, returnData=FALSE, pcs = c(1,2))
{
 stopifnot(length(pcs) == 2)    ### added this to check number of PCs ####
  # calculate the variance for each gene
  rv <- rowVars(assay(object))
  # select the ntop genes by variance
  select <- order(rv, decreasing=TRUE)[seq_len(min(ntop, length(rv)))]
  # perform a PCA on the data in assay(x) for the selected genes
  pca <- prcomp(t(assay(object)[select,]))
  # the contribution to the total variance for each component
  percentVar <- pca$sdev^2 / sum( pca$sdev^2 )
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, drop=FALSE])
  # add the intgroup factors together to create a new grouping factor
  group <- if (length(intgroup) > 1) {
    factor(apply( intgroup.df, 1, paste, collapse=" : "))
  } else {
    colData(object)[[intgroup]]
  }
  
  # extract loadings
  rot <- pca$rotation
  arot <- abs(rot)
  relrot <- sweep(arot, 2, colSums(arot), "/")
  #row.names(relrot) <- rowData(object)$IDGeneInfo[select]
  return(relrot)
}
#https://stackoverflow.com/questions/12760108/principal-components-analysis-how-to-get-the-contribution-of-each-parameter
```

## PCA Plot
PCA ggplot2 functions
```{r, echo=FALSE}
ggPCA <- function(rld, samples, condcolors, ntop = 500,  pclab = c(1,2)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony)) +
  geom_point(size=4, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "% variance")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "% variance")) + 
  coord_fixed(1) + 
  ggtitle("Principal Component Analysis")

PCAplot + 
  scale_color_manual(values=condcolors, name="Treatment") + 
  scale_shape_manual(values=colshapes, name="Colony") +
  theme(legend.position = "right")
}
```

```{r}
#pdf(file = "~/computing/scripts/EAPSI_anti-master/DESeqresults_Pdam/figures/PCAs.pdf", height = 4, width = 4.25)
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,2))
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,3))
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,4))
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(2,3))
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(2,4))
ggPCA(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(3,4))
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_heat-master/DESeqresults_Pdam/figures/PCAs.pdf", height = 4, width = 4.25)
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,2))
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,3))
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,4))
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(2,3))
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(2,4))
ggPCA(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(3,4))
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_anti.heat-master/DESeqresults_Pdam/figures/PCAs.pdf", height = 4, width = 4.25)
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,2))
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,3))
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,4))
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(2,3))
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(2,4))
ggPCA(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(3,4))
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH.pdf", height = 4, width = 8)
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,2))
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,3))
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,4))
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(2,3))
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(2,4))
ggPCA(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(3,4))
```

Add ellipses to better delinate large patterns
```{r, echo=FALSE}
ggPCA_O_geno <- function(rld, samples, condcolors, ntop = 500,  pclab = c(1,2)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony, group=samples$Colony)) +
    stat_ellipse(aes(fill = samples$Colony), geom = "polygon", type = "norm", alpha = 0.5) +
  geom_point(size=6, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "% variance")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "% variance")) + 
  ggtitle("Principal Component Analysis")

PCAplot + 
  scale_color_manual(values=condcolors, name="Treatment") +
  scale_fill_manual(values=colcolors, name="Colony") +
  scale_shape_manual(values=colshapes, name="Colony") +
  theme(legend.position = "right")
}
```

```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures_MBE702/PCA_0_geno_AXH.pdf", height = 5.25, width = 8.5)
ggPCA_O_geno(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,2)) +
    #coord_fixed(ratio = 19/34) + 
    ggtitle("") +
    theme(plot.title = element_text(size = 24),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 18),
        legend.text = element_text(size = 16))
```

```{r, echo=FALSE}
ggPCA_O_trmt <- function(rld, samples, condcolors, ntop = 500,  pclab = c(1,2)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony, group=samples$Treatment)) +
    stat_ellipse(aes(fill = samples$Treatment), geom = "polygon", type = "norm", alpha = 0.1) +
  geom_point(size=6, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "% variance")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "% variance")) + 
  coord_fixed(1) + 
  ggtitle("Principal Component Analysis")

PCAplot + 
  scale_color_manual(values=condcolors, name="Treatment") +
  scale_fill_manual(values = condcolors, name="Treatment") +
  scale_shape_manual(values=colshapes, name="Colony") +
  theme(legend.position = "right")
}
```

```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCA_0_trmt_AXH.pdf", height = 5.5, width = 8.5)
ggPCA_O_trmt(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,2)) +
      theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 14),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 12))
```


Facetted PCA functions for separating groups with same coordinates
```{r, echo=FALSE}
ggPCA_geno <- function(rld, samples, condcolors, pclab = c(1,2)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony)) +
  geom_point(size=4, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "% variance")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "% variance")) + 
  coord_fixed() + 
  ggtitle("Principal Component Analysis", subtitle = "Overall transcriptome expression data")

PCAplot + 
  scale_color_manual(values=condcolors) + 
  scale_shape_manual(values=colshapes) +
  theme(legend.position = "right") +
  facet_wrap(~samples$Colony)

}
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH.pdf", height = 4, width = 8)
ggPCA_geno(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,2))
ggPCA_geno(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,3))
ggPCA_geno(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(2,3))
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH.pdf", height = 4, width = 8)
ggPCA_geno(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,2))
ggPCA_geno(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,3))
ggPCA_geno(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(2,3))
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH.pdf", height = 4, width = 8)
ggPCA_geno(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,2))
ggPCA_geno(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,3))
ggPCA_geno(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(2,3))
```
```{r}
#pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH.pdf", height = 4, width = 8)
ggPCA_geno(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,2))
ggPCA_geno(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,3))
ggPCA_geno(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(2,3))
```

```{r, echo=FALSE}
ggPCA_trmt <- function(rld, samples, condcolors, pclab = c(1,2)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony)) +
  geom_point(size=4, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "% variance")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "% variance")) + 
  coord_fixed() + 
  ggtitle("Principal Component Analysis", subtitle = "Overall transcriptome expression data")

PCAplot + 
  scale_color_manual(values=condcolors) + 
  scale_shape_manual(values=colshapes) +
  theme(legend.position = "right") +
  facet_wrap(~samples$Treatment)

}
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_anti_ctrl.pdf", height = 4, width = 8)
ggPCA_trmt(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,2))
ggPCA_trmt(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(1,3))
ggPCA_trmt(rld_anti, stable_samples_anti, condcolors_anti, pclab = c(2,3))
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_heat_ctrl.pdf", height = 4, width = 8)
ggPCA_trmt(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,2))
ggPCA_trmt(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(1,3))
ggPCA_trmt(rld_heat, stable_samples_heat, condcolors_heat, pclab = c(2,3))
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_anti.heat_ctrl.pdf", height = 4, width = 8)
ggPCA_trmt(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,2))
ggPCA_trmt(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(1,3))
ggPCA_trmt(rld_anti.heat, stable_samples_anti.heat, condcolors_anti.heat, pclab = c(2,3))
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_AXH_colfacet.pdf", height = 4, width = 8)
ggPCA_trmt(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,2))
ggPCA_trmt(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(1,3))
ggPCA_trmt(rld_antixheat, stable_samples_antixheat, condcolors_antixheat, pclab = c(2,3))
```


Genotype-specific DESeq models PCA plots
```{r, echo=FALSE}
ggPCA_col <- function(rld, samples, condcolors = condcolors_antixheat, ntop = 500,  pclab = c(1,2), colshapes = c(18, 9, 16, 10)) {
  
PCAtmtdata <- plotPCA.custom(rld, intgroup = c("Treatment"), ntop = 500, returnData = TRUE,  pcs = c(pclab[1],pclab[2]))

PCAtmtpercentVar <- round(100* attr(PCAtmtdata, "percentVar"))

PCAplot <- ggplot(PCAtmtdata, aes(PCAtmtdata$PC1, PCAtmtdata$PC2, color=samples$Treatment, shape=samples$Colony)) +
  geom_point(size=6, show.legend = TRUE) + xlab(paste0( "PC", pclab[1], ": ", PCAtmtpercentVar[pclab[1]], "%")) + 
  ylab(paste0( "PC", pclab[2], ": ", PCAtmtpercentVar[pclab[2]], "%")) + 
  coord_fixed(1)

PCAplot + 
  scale_color_manual(values=condcolors, name = "Treatment") +
       theme(plot.title = element_text(size = 18),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 14),
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 12),
        legend.position = "none")
}
```
```{r, message=FALSE}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/PCAs_colony_AXH.pdf", height = 5.5, width = 8.5)
gHW1 <- ggPCA_col(rld_HW1, stable_samples_HW1, pclab = c(1,2))
 gHW1 + scale_shape_manual(values=colshapes[1], name = "Colony") +
        ggtitle("Houwan1")
gHW2 <- ggPCA_col(rld_HW2, stable_samples_HW2, pclab = c(1,2))
 gHW2 + scale_shape_manual(values=colshapes[2], name = "Colony") +
        ggtitle("Houwan2")
gWT1 <- ggPCA_col(rld_WT1, stable_samples_WT1, pclab = c(1,2))
 gWT1 + scale_shape_manual(values=colshapes[3], name = "Colony") +
        ggtitle("Wanglitung1")
gWT2 <- ggPCA_col(rld_WT2, stable_samples_WT2, pclab = c(1,2))
 gWT2 + scale_shape_manual(values=colshapes[4], name = "Colony") + 
        ggtitle("Wanglitung2")
```


```{r}
#PCA_loads_LPS <- as.data.frame(PCA.load(rld_LPS, intgroup = c("Treatment", "Colony"), ntop = 500, returnData = FALSE,  pcs = c(1,2)))
```

```{r}
#LPS_loads_HW1 <- as.data.frame(PCA.load(rld_HW1, intgroup = c("Treatment"), ntop = 50, returnData = TRUE,  pcs = c(1,2)))
#LPS_loads_HW2 <- as.data.frame(PCA.load(rld_HW2, intgroup = c("Treatment"), ntop = 50, returnData = TRUE,  pcs = c(1,2)))
#LPS_loads_WT1 <- as.data.frame(PCA.load(rld_WT1, intgroup = c("Treatment"), ntop = 50, returnData = TRUE,  pcs = c(1,2)))
#LPS_loads_WT2 <- as.data.frame(PCA.load(rld_WT2, intgroup = c("Treatment"), ntop = 50, returnData = TRUE,  pcs = c(1,2)))
```

