---
title: "AXH_DESeq-UpSetR_Pdam"
author: "Mike Connelly"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/scripts/EAPSI_AntiXHeat-master/")
```
## Setup packages and working directories
```{r packages, error=FALSE, warning=FALSE, message=FALSE}
library("tidyverse")
library("DESeq2")
library("UpSetR")
```
```{r}
movies <- read.csv( system.file("extdata", "movies.csv", package = "UpSetR"), header=T, sep=";" )
```

```{r}
DEGlists <- list(Heat = ressig_heat_ctrl$IDGeneInfo, Antibiotics = ressig_anti_ctrl$IDGeneInfo, Antibiotics.Heat = ressig_anti.heat_ctrl$IDGeneInfo)
```
```{r}
upset(fromList(DEGlists))
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_AntiXHeat-master/DESeqresults_Pdam/figures/UpSet_AXH.pdf", height = 6, width = 8.5)
upset(fromList(DEGlists), 
      sets = c("Antibiotics.Heat", "Antibiotics", "Heat"),
      keep.order = TRUE,
      order.by = "degree",
      decreasing = FALSE,
      empty.intersections = "on",
      mb.ratio = c(0.5, 0.5),
      point.size = 4, line.size = 2,
      text.scale = c(2, 1.5, 2, 1, 2, 1.5),
      sets.bar.color = c("#FFCC33", "#00CCCC", "#FF6600"),
      main.bar.color = c("#FF6600", "#00CCCC", "#FFCC33", rep("black", 4)))
```


```{r}
DEGlists2 <- list(heat_up = ressig_heat_ctrl_up$IDGeneInfo, anti_up = ressig_anti_ctrl_up$IDGeneInfo, anti.heat_up = ressig_anti.heat_ctrl_up$IDGeneInfo)
```
```{r}
upset(fromList(DEGlists2))
```
```{r}
DEGlists3 <- list(heat_dn = ressig_heat_ctrl_dn$IDGeneInfo, anti_dn = ressig_anti_ctrl_dn$IDGeneInfo, anti.heat_dn = ressig_anti.heat_ctrl_dn$IDGeneInfo)
```
```{r}
upset(fromList(DEGlists3))
```