---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/scripts/EAPSI.HW-WT-master/")
```
## Setup packages and working directories
```{r packages, error=FALSE, warning=FALSE, message=FALSE}
library("tidyverse")
library("DESeq2")
library("VennDiagram")
```
```{r}
DElists <- list.files(path = "./DESeqresults_Pdam/lists", pattern = "_ID.txt", full.names = TRUE)
```
```{r}
nrow(read.delim(DElists[1], header = FALSE))
```

```{r}
venn.plot <- draw.pairwise.venn(area1 = 187, area2 = 142, cross.area = 41, category = c("LPS", "Antibiotics"))
```

```{r}
grid.newpage()
draw.pairwise.venn(area1 = 187, area2 = 142, cross.area = 41, category = c("LPS", "Antibiotics"))
```
```{r}
venn_overall <- read.csv("./DESeqresults_Pdam/venn/jVenn_overall.csv")
venn_up <- read.csv("./DESeqresults_Pdam/venn/jVenn_up.csv")
venn_down <- read.csv("./DESeqresults_Pdam/venn/jVenn_dn.csv")
```

```{r}
LPSvenn <- as.character(venn_up$LPS.ctrl.AHL.ctrl)
LPSvenn
```
```{r}
ncol(venn_overall)
```

 
